### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by roysG** [ypresto/android-transcoder#21]
xxx-xxx :camoout Admin$ sudo cordova plugin add https://github.com/ypresto/android-transcoder.git

Fetching plugin "https://github.com/ypresto/android-transcoder.git" via git clone
Repository "https://github.com/ypresto/android-transcoder.git" checked out to git ref "master".
Failed to fetch plugin https://github.com/ypresto/android-transcoder.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	CordovaError: Cannot find plugin.xml for plugin '1463437390750'. Please try adding it again.

??

**Comment by ypresto** [comment]
Cordova plugin requires [plugin.xml](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html) and this library is NOT a cordova plugin.
Please create your own cordova plugin for the library.
