### ISSUE TITLE
Run on GPU

### ISSUE THREAD

**Issue by grosalex** [ypresto/android-transcoder#28]
Hi,
First of all thanks for the lib it's amazing.

Just a question is there a way to make it works on android gpu ?

Regards

**Comment by ypresto** [comment]
This library runs on hardware :)

It uses MediaCodec which is interface for hardware (perhaps DSP or GPU, but I'm not sure which is actually used) codec. All modern devices should have hardware avc (h.264) encoder in SoC to record video.

However there is [software codec in Android's source code](https://android.googlesource.com/platform/frameworks/av/+/90a92053219ae50ddf4bb54e3d54db2d309e2b8d/media/libstagefright/codecs/avc/), so it can be used if the device has no hardware support.

**Comment by grosalex** [comment]
Ok thanks for the answear.

Regards,
