### ISSUE TITLE
Transcoding of 720p videos

### ISSUE THREAD

**Issue by kriztan** [ypresto/android-transcoder#39]
Hi. Is it possible to transcode videos with resolutions smaller than 1080p? I've setup a lower bitrate to compress the video a bit more, but 720p videos were not transcoded. 
Thanks

**Comment by ypresto** [comment]
You can define your own `MediaFormatStrategy` to use custom resolution.
But it is not guaranteed to work on all device; there is limitation of hardware codec.
See https://github.com/ypresto/android-transcoder/issues/40#issuecomment-277697028
