### ISSUE TITLE
can only convert mp4 to mp4

### ISSUE THREAD

**Issue by samuelt1** [ypresto/android-transcoder#42]
I tried to convert a whole bunch of different stuff on android, and they all failed except mp4. which does not help, because it is mp4 already. Maybe I should put this elsewhere because it is the converter that is actually failing.
You can try the videos I did here: 
[https://cinelerra-cv.org/footage.php](https://cinelerra-cv.org/footage.php)
and 
[http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5](http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5)

here is the errors i got from them:
java.io.IOException: Failed to instantiate extractor.
java.lang.IllegalArgumentException: extractor does not contain video and/or audio tracks.
net.ypresto.androidtranscoder.engine.InvalidOutputFormatException: Audio codecs other than AAC is not supported, actual mime type: audio/3gpp

**Comment by ypresto** [comment]
Note: Originally this library is intended to shrink high resolution mp4 to lower resolution appropriate for upload.

Your video file contains "audio/3gpp", perhaps it is AMR, is not suitable for mp4 container.
You can specify audio bitrate and enforce transcoding to AAC in this library, while default is passthrough and no audio transcoding is happen.

**Comment by pravinpatil83** [comment]
Hi, I am getting this issue too. How to enforce transcoding to use AAC in this library?

**Comment by pravinpatil83** [comment]
The file I am trying has audio/eac3 as a first track and audio/mp4a-latm second.

**Comment by ypresto** [comment]
@pravinpatil83 You can use Android720pFormatStrategy() and pass audio bitrate to enforce audio transcoding.

**Comment by richmonkey** [comment]
mp4 can contain the AMR audio.
MediaStore.EXTRA_VIDEO_QUALITY is 0, i got the mp4 file which contains AMR audio.

**Comment by qandeelabbassi** [comment]
@ypresto how to know optimal audio bitrate?
