### ISSUE TITLE
Sometimes, "mFuture.cancel(true);" doesn't work

### ISSUE THREAD

**Issue by strayerM** [ypresto/android-transcoder#45]
Sometimes, "mFuture.cancel(true);" doesn't work when I want to stop the transcoding. It will happen, if I transcode a particular video, and other videos are fine. What is the reason of this?

**Comment by morankaifa** [comment]
@ypresto I know the reason for this bug , in the Class [**MediaTranscoderEngine**](https://github.com/ypresto/android-transcoder/blob/master/lib/src/main/java/net/ypresto/androidtranscoder/engine/MediaTranscoderEngine.java) , the function **runPipelines** has the following code block :
`if (!stepped) {
    try {
          Thread.sleep(SLEEP_TO_WAIT_TRACK_TRANSCODERS);
    } catch (InterruptedException e) {
           // nothing to do
    }
 }`
 . Why don't you do anything when you catch the **InterruptedException** ? In my opinion , you should **re-throw** the **InterruptedException** .

**Comment by ypresto** [comment]
Yeah that's just bug..! (ugh, just bad code... >_<) 
Could you PR..?

**Comment by PinkFloyded** [comment]
So the way to fix this would be to change the signature of `runPipelines()` method to `private void runPipelines() throws InterruptedException` and add a catch block in `transcodeVideo()` to rethrow it right? Shall I PR for this?

**Comment by tingfengainiaini** [comment]
@PinkFloyded @ypresto Either just remove the try catch clause of Thread.sleep() or just rethrow the exception, can not cancel the task. We could add !Thread.currentThread().isInterrupted() check to runPipelines() while loop condition. Although, that this check in while loop also can not cancel the tasks did with ThreadPoolExcutor sometimes (if the while working is too fast and has 'no interval' to be interrunpted), but here, it is enough in our case.
