### ISSUE TITLE
use small resolution doesn't reduce the output size

### ISSUE THREAD

**Issue by xiaobaDev** [ypresto/android-transcoder#46]
Android720pFormatStrategy
Android480pFormatStrategy
Android1080pFormatStrategy

the result mp4 size of these is same
how to optmize it?

**Comment by morankaifa** [comment]
Size of the result MP4 file mainly depends on video's bitrate.

**Comment by xiaobaDev** [comment]
reduce the bitrate from 8k to 3k, the result is same

**Comment by ypresto** [comment]
strange, can you try example app in this repo?
