### ISSUE TITLE
why its not working on  kitkat &  lollipop  devices ?

### ISSUE THREAD

**Issue by monikarora** [ypresto/android-transcoder#47]
Hey , in marshmallow its working fine but not woking in 4.4.2 kitkat & lollipop devices ?
Please help me

**Comment by ypresto** [comment]
Detail of device and full stack trace please :)

**Comment by monikarora** [comment]
Panasonic T40 4.4.2 & HTC Desire 620G 4.4.2  in both devices  its not working

**Comment by ypresto** [comment]
Without stack trace I can't inspect cause of the issue :(

**Comment by monikarora** [comment]
![screenshot from 2017-04-11 14 37 42](https://cloud.githubusercontent.com/assets/17878500/24901488/dad8c4f2-1ec4-11e7-825b-00065ef1796b.png)
select video from gallery get this error

**Comment by ypresto** [comment]
It seems that input video is not 16:9 resolution as stack trace says.
And it is not supported by this library for now.

See https://github.com/ypresto/android-transcoder/issues/40#issuecomment-277697028

**Comment by monikarora** [comment]
:( ok

**Comment by ypresto** [comment]
Ah, I understood. 1920x1080 in mp4 is (actually) coded in 1920x1088 because 1080 is not multiple of 16.
Decoder should crop remainder 8 pixel rows, but decoder of your device returns original resolution...
It is bug of your device's codec, i think, unfortunately..

**Comment by ypresto** [comment]
Workaround is to add per-device fix to crop remainder rows. PR is welcomed.
