### ISSUE TITLE
Crash application when transcoding m4v file.

### ISSUE THREAD

**Issue by CuongSmile** [ypresto/android-transcoder#5]
Hi @ypresto ,

Thanks you because created a library very useful .

I've tested your library on some devices :  Galaxy S3 (4.3), Nexus 5 (4.4.2) ... but when i try transcode a video has format .m4v or 3gp on Galaxy S3 (4.3) , an error appearing and crash this test application.

It's logcat : 
```
03-17 09:43:22.380: D/dalvikvm(13507): GC_FOR_ALLOC freed 1144K, 35% free 14266K/21724K, paused 63ms, total 63ms
03-17 09:43:24.470: V/MediaExtractor(13507): Autodetected media content as 'video/mp4' with confidence 0.40
03-17 09:43:24.485: D/MediaTranscoderEngine(13507): Duration (us): 60127000
03-17 09:43:24.495: I/OMXClient(13507): Using client-side OMX mux.
03-17 09:43:24.520: I/ACodec(13507): setupVideoEncoder succeeded
03-17 09:43:24.555: I/OMXClient(13507): Using client-side OMX mux.
03-17 09:43:24.925: E/ACodec(13507): ## 3d, eNativeColorFormat 0x15
03-17 09:43:24.925: E/ACodec(13507): ## 3d, eNativeColorFormat 0x105
03-17 09:43:25.070: V/VideoTrackTranscoder(13507): Added track #0 with video/avc to muxer
03-17 09:43:25.100: D/dalvikvm(13507): GC_FOR_ALLOC freed 289K, 35% free 14255K/21724K, paused 29ms, total 29ms
03-17 09:43:25.100: I/MPEG4Writer(13507): setStartTimestampUs: 200200
03-17 09:43:25.100: I/MPEG4Writer(13507): Earliest track starting time: 200200
03-17 09:43:25.105: I/MPEG4Writer(13507): setStartTimestampUs: 0
03-17 09:43:25.105: I/MPEG4Writer(13507): Earliest track starting time: 0
03-17 09:43:25.160: A/MPEG4Writer(13507): frameworks/av/media/libstagefright/MPEG4Writer.cpp:2517 CHECK_GE( timestampUs,0ll) failed: -200200 vs. 0
03-17 09:43:25.160: A/libc(13507): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 13995 (VideoTrackEncod)
```

But when I try transcode this video on Nexus 5, it transcode completed.

Thanks you :)

**Comment by ypresto** [comment]
Thanks for reporting issue!

> Earliest track starting time: 200200

It seems problem around detecting presentation time (offset).

Can you share failing video files for investigation?
Metadata (profile, level, resolution, etc...) is also welcomed.

Note that Android only (officially) supports "baseline profile" mp4 files.

**Comment by ypresto** [comment]
@CuongSmile

FYI: I recently fixed bug that library hangs in native layer when incompatible video file is passed.
It just throws Exception in such situation before start transcoding. :)

**Comment by CuongSmile** [comment]
Hi @ozyozyo 

Thanks form caring my issue.

I'm really sorry you because I don't remember rely you about this issue, util I received a email nofification from github send to my email.

About this issue, I remembered when I debug I found the problem occur when decoce video, it related to presentation time, I must re-calculated the presentation time when transcode video.

**Comment by ypresto** [comment]
Please reopen if similar issue happens. Thanks..!
