### ISSUE TITLE
cordova build still failing 

### ISSUE THREAD

**Issue by faustoct** [ypresto/android-transcoder#51]
gets the error
Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 18 declared in library [com.github.ergovia-mobile:android-transcoder:v0.1.10R_ergovia] /Users/fausto/Projects/coding/4linked-mobile/club-sencha/phonegap/platforms/android/build/intermediates/exploded-aar/com.github.ergovia-mobile/android-transcoder/v0.1.10R_ergovia/AndroidManifest.xml

tried to add sdk-use <uses-sdk tools:overrideLibrary="net.ypresto.androidtranscoder" />
to work with minsdk 9 but not working !

**Comment by ypresto** [comment]
You are referencing [a fork of this library](https://github.com/ergovia-mobile/android-transcoder).
Please use `net.ypresto.androidtranscoder:android-transcoder` or open PR for the fork repo.
