### ISSUE TITLE
Release notes for version 0.3.0?

### ISSUE THREAD

**Issue by edwardotis** [ypresto/android-transcoder#66]
I saw a 0.3.0 release was pushed 6 days ago after a 2 year hiatus of releases.
https://github.com/ypresto/android-transcoder/releases/tag/v0.3.0

@ypresto, could you share what's new in this version?

Thank you

**Comment by ypresto** [comment]
Please see [CHANGELOG](https://github.com/ypresto/android-transcoder/blob/master/CHANGELOG.md) :)

**Comment by edwardotis** [comment]
Thanks, @ypresto :)
