### ISSUE TITLE
Add a synchronous method to MediaTranscoder

### ISSUE THREAD

**Issue by ralphpina** [ypresto/android-transcoder#9]
Currently, all ```transcodeVideo``` methods in ```MediaTranscoder``` are async methods. However, there are many situations where a synchronous method might be preferable. IntentServices and Handlers with their own HanderThread are two that quickly come to mind. Would you be open to a PR to add a synchronous method? I was thinking of pretty much copying/pasting the current work that ```transcodeVideo``` does, like so:

```java
public void transcodeVideo(final FileDescriptor inFileDescriptor, final String outPath, final MediaFormatStrategy outFormatStrategy, final Listener listener) throws IOException, RuntimeException {
    MediaTranscoderEngine engine = new MediaTranscoderEngine();
    engine.setProgressCallback(new MediaTranscoderEngine.ProgressCallback( {
        @Override
         public void onProgress(final double progress) {
             listener.onTranscodeProgress(progress);
         }
    });
    engine.setDataSource(inFileDescriptor);
    engine.transcodeVideo(outPath, outFormatStrategy);
}
```

I figure that if you are running this synchronously you know what you are doing and you can handle your own Exceptions/failures. You'll know it was successful when it returned. The only listener call that you might be interested in is for progress?

**Comment by ypresto** [comment]
I have same issue on app which uses this library. Currently doing patch work with CountDownLatch...
I think it is good idea to provide sync version of the method.

Note that there are some reasons using async interface and thread pool:

- [Cannot run in Thread with Looper (a.k.a. HandlerThread, IntentService)](https://github.com/ypresto/android-transcoder/blob/de9279fadeeed1d06a86633d05a13e848998dd92/lib/src/main/java/net/ypresto/androidtranscoder/engine/OutputSurface.java#L93)
- [Use only one thread to keep from exhausting device resources](
https://github.com/ypresto/android-transcoder/blob/48afb1fec122039c802aa15888ae38d81a591ba9/lib/src/main/java/net/ypresto/androidtranscoder/MediaTranscoder.java#L43)

So sync version would be better to use same thread pool than async version.

**Comment by ypresto** [comment]
We're currently working on `Future`. It also can be passed to `Observable.from()`!

**Comment by ypresto** [comment]
v0.1.10 returns Future. Please use Future.get()!
